const LOGIN_REQUEST = 'LOGIN_REQUEST'
const LOGIN_FAIL = 'LOGIN_FAIL'
const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
const LOGOUT_SUCCES = 'LOGOUT_SUCCESS'
const REGISTER_SUCCES = 'REGISTER_SUCCES'
const REGISTER_REQUEST = 'REGISTER_REQUEST'
const REGISTER_FAIL = 'REGISTER_FAIL'
const REREGISTER_REQUEST = 'REREGISTER_REQUEST'
const REGISTER_INVALID = 'REGISTER_INVALID'
const LOGIN_INVALID = 'LOGIN_INVALID'
const ADD_REQUEST = 'ADD_REQUEST'
const REMOVE_REQUEST = 'REMOVE_REQUEST'
const REMOVE_SUCCES = 'REMOVE_SUCCES'
const ADD_COMPLETE = 'ADD_COMPLETE'
const CLEAR_REAQUESTS = 'CLEAR_REAQUESTS'

const graphTypes = {
  LOGIN_REQUEST,
  LOGIN_FAIL,
  LOGIN_SUCCESS,
  LOGOUT_SUCCES,
  REGISTER_SUCCES,
  REGISTER_REQUEST,
  REGISTER_FAIL,
  REREGISTER_REQUEST,
  REGISTER_INVALID,
  LOGIN_INVALID,
  ADD_REQUEST,
  REMOVE_REQUEST,
  REMOVE_SUCCES,
  ADD_COMPLETE,
  CLEAR_REAQUESTS,
}

export default graphTypes
